Provide partial test suite for header validation
pragma-org/ouroboros pull request #3
Opened 2024-10-24 08:38 UTC by abailly

This PR builds upon @AndrewWestberg's work on Praos headers validation, adding more tests in the form of JSON-formatted pairs of a context and a header, which may or may not be valid. A single test function loads the test vectors and iterates through the various headers, calling validation code and verifying the result. These tests increase code coverage from ~75% to ~95%.

In the course of writing these tests, I found a few minor issues I fixed in the validation code:

* Adding a special case for when the header's producer has 100% of the stake (which lead me to report [this issue](https://github.com/txpipe/pallas/issues/529)), which obviously is not a real case but is nevertheless accounted for in Haskell code and useful
* Using pool id instead of raw bytes as key to operational certificate counters' the consensus code maintains 
* Expose active slot coefficient from ledger instead of derived `c` value (ran the benchmarks locally and did not notice any significant impact), because of first point above
* Switch position for tests on operational counters as otherwise it could lead to runtime `panic` from underflow
* A couple more expressive error messages

There's more work that needs to be done to cover more of the validation process, which I plan to add in another PR:

* Vary stake distributions
* Cover VRF proof related checks

2024-10-24 08:39 UTC, abailly commented
Consensus code PR: https://github.com/IntersectMBO/ouroboros-consensus/pull/1285

2024-10-26 13:14 UTC, AndrewWestberg commented
Rebase on top of `main` since I merged my previous PR. It should be a minimal ff rebase for you.

2024-10-26 13:22 UTC, AndrewWestberg commented on ouroboros-praos/Cargo.toml
> +base64 = "0.22.1"
test vectors are not using base64 encoding any long. We can remove this dependency.

2024-10-26 13:23 UTC, AndrewWestberg approved these changes
Should be good to merge after rebasing. This is a good base to add additional tests for opcert mutations, etc on top of.

2024-10-28 13:53 UTC, AndrewWestberg requested changes
Ensure we are using conventional commit messages.

https://www.conventionalcommits.org/en/v1.0.0/#summary

2024-11-08 13:11 UTC, abailly commented
@AndrewWestberg Can we merge this? It's been a while...

2024-11-08 16:26 UTC, AndrewWestberg approved these changes

2024-11-12 14:05 UTC, merged